CREATE TABLE Utente (

UtenteID INT PRIMARY KEY IDENTITY (1,1),
Nome VARCHAR (250) NOT NULL,
Cognome VARCHAR (250) NOT NULL,
Email VARCHAR (250)  UNIQUE NOT NULL,
);



CREATE TABLE Libro (

LibroID INT PRIMARY KEY IDENTITY (1,1),
Titolo VARCHAR (250) NOT NULL,
Anno DATE NOT NULL,
Disponibile BIT NOT NULL,
);


CREATE TABLE Prestito (

UtenteID INT PRIMARY KEY IDENTITY (1,1),
DataPrestito DATE  NOT NULL,
DataRitorno VARCHAR NOT NULL,
utenteRIF INT, 
libroRIF INT, 
FOREIGN KEY (utenteRIF) REFERENCES Utente(UtenteID),
FOREIGN KEY (libroRIF)REFERENCES Utente(UtenteID)

);
